export enum FacturaEstado {
  PENDIENTE = 'PENDIENTE',
  PAGADO = 'PAGADO',
  ANULADA = 'ANULADA',
}

export enum CajaEstado {
  ABIERTA = 'ABIERTA',
  CERRADA = 'CERRADA',
  ANULADA = 'ANULADA',
}

export enum CitaEstado {
  PROGRAMADA = 'PROGRAMADA',
  CONFIRMADA = 'CONFIRMADA',
  EN_PROCESO = 'EN PROCESO',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
}

export enum CompraEstado {
  PENDIENTE = 'PENDIENTE',
  COMPLETADA = 'COMPLETADA',
  ANULADA = 'ANULADA',
}

export enum CotizacionEstado {
  GENERADA = 'GENERADA',
  CADUCADA = 'CADUCADA',
}

export enum RecepcionEstado {
  PENDIENTE = 'PENDIENTE',
  EN_PROCESO = 'EN PROCESO',
  FINALIZADO = 'FINALIZADO',
  ENTREGADO = 'ENTREGADO',
}

export enum RecepcionSeguimientoEstado {
  PENDIENTE_DIAGNOSTICO = 'PENDIENTE DE DIAGNOSTICO',
  ESPERA_APROBACION = 'ESPERA APROBACION',
  EN_REPARACION = 'EN REPARACION',
  EN_ESPERA_REPUESTOS = 'EN ESPERA REPUESTOS',
  PRUEBAS = 'PRUEBAS',
  LISTO_PARA_ENTREGAR = 'LISTO PARA ENTREGAR',
  CANCELADO = 'CANCELADO',
}

export enum TramiteSeguroEstado {
  INICIADO = 'INICIADO',
  EN_REVISION = 'EN REVISION',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  CERRADO = 'CERRADO',
}

export enum EstadoActivo {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
}
